/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Atel Dot Net
 */
public class NewAdminAdd extends javax.swing.JFrame {

    private ImageIcon icon;
    /**
     * Creates new form NewAdminAdd
     */
    public NewAdminAdd() {
        initComponents();
        SetIcon();
    }
 public void SetIcon()
    {
        icon=new ImageIcon(getClass().getResource("shop32.png"));
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        OldUserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        OldPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        NewUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NewPassword = new javax.swing.JPasswordField();
        SubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEW ADMIN ADD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 20, 400, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(530, 0, 850, 140);

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopmanagement/a.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 100, 520, 560);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 530, 730);

        jPanel22.setBackground(new java.awt.Color(0, 0, 204));
        jPanel22.setLayout(null);
        getContentPane().add(jPanel22);
        jPanel22.setBounds(550, 150, 20, 540);

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(580, 150, 740, 20);

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.setLayout(null);
        getContentPane().add(jPanel4);
        jPanel4.setBounds(1330, 150, 20, 540);

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));
        jPanel5.setLayout(null);
        getContentPane().add(jPanel5);
        jPanel5.setBounds(580, 670, 740, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ADMIN NAME             :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(640, 190, 200, 50);

        OldUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OldUserName.setForeground(new java.awt.Color(0, 0, 204));
        OldUserName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(OldUserName);
        OldUserName.setBounds(900, 200, 300, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("ADMIN PASSWORD  :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(640, 260, 200, 50);

        OldPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OldPassword.setForeground(new java.awt.Color(0, 0, 204));
        OldPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OldPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(OldPassword);
        OldPassword.setBounds(900, 270, 300, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("NEW ADMIN              :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 330, 200, 60);

        NewUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NewUserName.setForeground(new java.awt.Color(0, 0, 204));
        NewUserName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(NewUserName);
        NewUserName.setBounds(900, 340, 300, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PASSWORD                :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 410, 200, 40);

        NewPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NewPassword.setForeground(new java.awt.Color(0, 0, 204));
        NewPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(NewPassword);
        NewPassword.setBounds(900, 410, 300, 40);

        SubmitButton.setBackground(new java.awt.Color(0, 0, 204));
        SubmitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("   SUBMIT");
        SubmitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitButton);
        SubmitButton.setBounds(900, 480, 170, 70);

        setSize(new java.awt.Dimension(1377, 769));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OldPasswordActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ShopManagement;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            String sql1 = "Select * from AdminLogin where UserName=? and Password =?";
            PreparedStatement pst1 = con.prepareStatement(sql1);

            pst1.setString(1, OldUserName.getText().toString());
            pst1.setString(2, OldPassword.getText().toString());
            ResultSet rs = pst1.executeQuery();

            if(rs.next())
            {

                String sql = "Insert into AdminLogin"
                +"(UserName,Password)"
                +"values(?,?)";
                PreparedStatement pst = con.prepareStatement(sql);

                pst.setString(1, NewUserName.getText().toString());
                pst.setString(2, NewPassword.getText().toString());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Successfully Registered");

                OldUserName.setText("");
                OldPassword.setText("");
                NewUserName.setText("");
                NewPassword.setText("");

                con.close();

            }
            else
            {
                JOptionPane.showMessageDialog(null, "Not Updated");
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAdminAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAdminAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAdminAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAdminAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAdminAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JTextField NewUserName;
    private javax.swing.JPasswordField OldPassword;
    private javax.swing.JTextField OldUserName;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
