/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopmanagement;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Atel Dot Net
 */
public class ProductControl extends javax.swing.JFrame {

    /**
     * Creates new form ProductControl
     */
    private ImageIcon icon;
    public ProductControl() {
        initComponents();
        SetIcon();
    }
 public void SetIcon()
    {
        icon=new ImageIcon(getClass().getResource("shop32.png"));
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        NewProductPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        OldProductPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ExitMenu = new javax.swing.JMenu();
        AddProductMenu = new javax.swing.JMenu();
        NewProductItem = new javax.swing.JMenuItem();
        OldProductItem = new javax.swing.JMenuItem();
        SellProductMenu = new javax.swing.JMenu();
        StockMenu = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        MemberInfoItem = new javax.swing.JMenuItem();
        DueBillItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(null);

        NewProductPanel.setBackground(new java.awt.Color(0, 204, 204));
        NewProductPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NewProductPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewProductPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewProductPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewProductPanelMouseExited(evt);
            }
        });
        NewProductPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEW PRODCUTS");
        NewProductPanel.add(jLabel1);
        jLabel1.setBounds(40, 20, 220, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopmanagement/NEWpRODUCT.png"))); // NOI18N
        NewProductPanel.add(jLabel2);
        jLabel2.setBounds(100, 70, 64, 90);

        jPanel2.add(NewProductPanel);
        NewProductPanel.setBounds(330, 250, 270, 180);

        OldProductPanel.setBackground(new java.awt.Color(0, 204, 204));
        OldProductPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OldProductPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OldProductPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OldProductPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OldProductPanelMouseExited(evt);
            }
        });
        OldProductPanel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("OLD PRODCUTS");
        OldProductPanel.add(jLabel3);
        jLabel3.setBounds(40, 20, 220, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopmanagement/oldproduct.png"))); // NOI18N
        OldProductPanel.add(jLabel4);
        jLabel4.setBounds(100, 70, 64, 90);

        jPanel2.add(OldProductPanel);
        OldProductPanel.setBounds(690, 250, 270, 180);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1340, 640);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setAlignmentX(1.0F);
        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(5, 5, 50, 50));

        ExitMenu.setBackground(new java.awt.Color(153, 153, 153));
        ExitMenu.setBorder(null);
        ExitMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Atel Dot Net\\Desktop\\IMAGE\\icon\\bb16.png")); // NOI18N
        ExitMenu.setText("BACK");
        ExitMenu.setDelay(100);
        ExitMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExitMenu.setMargin(new java.awt.Insets(0, 0, 0, 50));
        ExitMenu.setPreferredSize(new java.awt.Dimension(105, 19));
        ExitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMenuMouseClicked(evt);
            }
        });
        ExitMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ExitMenuKeyPressed(evt);
            }
        });
        jMenuBar1.add(ExitMenu);

        AddProductMenu.setBackground(new java.awt.Color(153, 153, 153));
        AddProductMenu.setBorder(null);
        AddProductMenu.setText("     ADD PRODUCT");
        AddProductMenu.setDelay(100);
        AddProductMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddProductMenu.setMargin(new java.awt.Insets(0, 0, 0, 50));
        AddProductMenu.setPreferredSize(new java.awt.Dimension(150, 20));
        AddProductMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProductMenuMouseClicked(evt);
            }
        });

        NewProductItem.setText("NEW PRODUCTS");
        NewProductItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NewProductItem.setPreferredSize(new java.awt.Dimension(150, 26));
        NewProductItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewProductItemMouseClicked(evt);
            }
        });
        NewProductItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProductItemActionPerformed(evt);
            }
        });
        AddProductMenu.add(NewProductItem);

        OldProductItem.setText("OLD PRODUCTS");
        OldProductItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OldProductItem.setPreferredSize(new java.awt.Dimension(150, 20));
        OldProductItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OldProductItemMouseClicked(evt);
            }
        });
        OldProductItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OldProductItemActionPerformed(evt);
            }
        });
        AddProductMenu.add(OldProductItem);

        jMenuBar1.add(AddProductMenu);

        SellProductMenu.setBackground(new java.awt.Color(153, 153, 153));
        SellProductMenu.setBorder(null);
        SellProductMenu.setText("      SELL PRODUCT");
        SellProductMenu.setDelay(100);
        SellProductMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SellProductMenu.setMargin(new java.awt.Insets(0, 0, 0, 50));
        SellProductMenu.setPreferredSize(new java.awt.Dimension(150, 20));
        SellProductMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellProductMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(SellProductMenu);

        StockMenu.setBackground(new java.awt.Color(153, 153, 153));
        StockMenu.setBorder(null);
        StockMenu.setText("            STOCK");
        StockMenu.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        StockMenu.setDelay(100);
        StockMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StockMenu.setMargin(new java.awt.Insets(0, 0, 0, 50));
        StockMenu.setPreferredSize(new java.awt.Dimension(150, 20));
        StockMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(StockMenu);

        jMenu6.setBackground(new java.awt.Color(153, 153, 153));
        jMenu6.setBorder(null);
        jMenu6.setText("          ACCOUNT");
        jMenu6.setDelay(100);
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(0, 0, 0, 50));
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 20));

        MemberInfoItem.setText(" MEMBER INFO");
        MemberInfoItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MemberInfoItem.setMargin(new java.awt.Insets(0, 0, 0, 50));
        MemberInfoItem.setPreferredSize(new java.awt.Dimension(150, 26));
        MemberInfoItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MemberInfoItemMouseClicked(evt);
            }
        });
        MemberInfoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberInfoItemActionPerformed(evt);
            }
        });
        jMenu6.add(MemberInfoItem);

        DueBillItem.setText(" DUE BILL");
        DueBillItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DueBillItem.setMargin(new java.awt.Insets(0, 0, 0, 50));
        DueBillItem.setPreferredSize(new java.awt.Dimension(127, 26));
        DueBillItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DueBillItemMouseClicked(evt);
            }
        });
        DueBillItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DueBillItemActionPerformed(evt);
            }
        });
        jMenu6.add(DueBillItem);

        jMenuBar1.add(jMenu6);

        jMenu1.setBackground(new java.awt.Color(153, 153, 153));
        jMenu1.setText("        REFRESH");
        jMenu1.setActionCommand("    REFRESH");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1354, 761));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NewProductPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewProductPanelMouseEntered
        // TODO add your handling code here:
        NewProductPanel.setBackground(Color.red);
    }//GEN-LAST:event_NewProductPanelMouseEntered

    private void NewProductPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewProductPanelMouseExited
        // TODO add your handling code here:
        NewProductPanel.setBackground(new java.awt.Color(0,204,204));
    }//GEN-LAST:event_NewProductPanelMouseExited

    private void OldProductPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OldProductPanelMouseEntered
        // TODO add your handling code here:
        OldProductPanel.setBackground(Color.red);
    }//GEN-LAST:event_OldProductPanelMouseEntered

    private void OldProductPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OldProductPanelMouseExited
        // TODO add your handling code here:
          OldProductPanel.setBackground(new java.awt.Color(0,204,204));
    }//GEN-LAST:event_OldProductPanelMouseExited

    private void NewProductPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewProductPanelMouseClicked
        // TODO add your handling code here:
        AddProduct obj=new AddProduct();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NewProductPanelMouseClicked

    private void OldProductPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OldProductPanelMouseClicked
        // TODO add your handling code here:
        AddOldProduct obj=new AddOldProduct();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OldProductPanelMouseClicked

    private void ExitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMenuMouseClicked
        // TODO add your handling code here:
        HomePage obj=new HomePage();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitMenuMouseClicked

    private void ExitMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ExitMenuKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_ExitMenuKeyPressed

    private void NewProductItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewProductItemMouseClicked
        // TODO add your handling code here:
        AddProduct obj=new AddProduct();
        obj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_NewProductItemMouseClicked

    private void OldProductItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OldProductItemMouseClicked
        // TODO add your handling code here:
        AddOldProduct obj=new AddOldProduct();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OldProductItemMouseClicked

    private void AddProductMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductMenuMouseClicked
        // TODO add your handling code here:
        // AddProduct obj=new AddProduct();
        // obj.setVisible(true);
        // this.dispose();

    }//GEN-LAST:event_AddProductMenuMouseClicked

    private void SellProductMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellProductMenuMouseClicked
        // TODO add your handling code here:
        SellProduct obj=new SellProduct();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellProductMenuMouseClicked

    private void StockMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMenuMouseClicked
        // TODO add your handling code here:
        StockInfo obj=new StockInfo();
        obj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_StockMenuMouseClicked

    private void MemberInfoItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberInfoItemMouseClicked
        // TODO add your handling code here:
        MemberAccount obj=new MemberAccount();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MemberInfoItemMouseClicked

    private void MemberInfoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberInfoItemActionPerformed
        // TODO add your handling code here:
        MemberAccount obj=new MemberAccount();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MemberInfoItemActionPerformed

    private void DueBillItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DueBillItemMouseClicked
        // TODO add your handling code here:
        DueBill obj=new DueBill();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DueBillItemMouseClicked

    private void DueBillItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DueBillItemActionPerformed
        // TODO add your handling code here:
        DueBill obj=new DueBill();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DueBillItemActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        HomePage obj=new HomePage();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void NewProductItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProductItemActionPerformed
        // TODO add your handling code here:
         AddProduct obj=new AddProduct();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NewProductItemActionPerformed

    private void OldProductItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OldProductItemActionPerformed
        // TODO add your handling code here:
          AddOldProduct obj=new AddOldProduct();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OldProductItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AddProductMenu;
    private javax.swing.JMenuItem DueBillItem;
    private javax.swing.JMenu ExitMenu;
    private javax.swing.JMenuItem MemberInfoItem;
    private javax.swing.JMenuItem NewProductItem;
    private javax.swing.JPanel NewProductPanel;
    private javax.swing.JMenuItem OldProductItem;
    private javax.swing.JPanel OldProductPanel;
    private javax.swing.JMenu SellProductMenu;
    private javax.swing.JMenu StockMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
