/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Atel Dot Net
 */
public class ShopInfo extends javax.swing.JFrame {

    /**
     * Creates new form ShopInfo
     */
    private ImageIcon icon;
    
    public ShopInfo() {
        initComponents();
        FetchData();
        SetIcon();
    }
  public void SetIcon()
    {
        icon=new ImageIcon(getClass().getResource("shop32.png"));
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SecurityText = new javax.swing.JTextField();
        ShopNameText = new javax.swing.JTextField();
        AddressText = new javax.swing.JTextField();
        PhoneText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        VatText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        VatNumberText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        ExitMenu = new javax.swing.JMenu();
        AddProductMenu = new javax.swing.JMenu();
        SellProductMenu = new javax.swing.JMenu();
        StockMenu = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        MemberInfoItem = new javax.swing.JMenuItem();
        DueBillItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SECURITY CODE  :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 480, 210, 40);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SHOP NAME         :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 80, 270, 40);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADDRESS               :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, 150, 270, 40);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PHONE                  :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 230, 270, 30);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EMAIL                    :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 300, 210, 30);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VAT NUMBER       :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(370, 420, 210, 40);

        SecurityText.setBackground(new java.awt.Color(153, 0, 153));
        SecurityText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SecurityText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(SecurityText);
        SecurityText.setBounds(600, 480, 530, 40);

        ShopNameText.setBackground(new java.awt.Color(153, 0, 153));
        ShopNameText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ShopNameText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ShopNameText);
        ShopNameText.setBounds(600, 80, 530, 40);

        AddressText.setBackground(new java.awt.Color(153, 0, 153));
        AddressText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddressText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(AddressText);
        AddressText.setBounds(600, 150, 530, 40);

        PhoneText.setBackground(new java.awt.Color(153, 0, 153));
        PhoneText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PhoneText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(PhoneText);
        PhoneText.setBounds(600, 220, 530, 40);

        EmailText.setBackground(new java.awt.Color(153, 0, 153));
        EmailText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmailText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(EmailText);
        EmailText.setBounds(600, 290, 530, 40);

        VatText.setBackground(new java.awt.Color(153, 0, 153));
        VatText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VatText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(VatText);
        VatText.setBounds(600, 360, 210, 40);

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopmanagement/UPDATE32.png"))); // NOI18N
        jButton1.setText("     UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(780, 540, 150, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopmanagement/256.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 50, 300, 510);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopmanagement/discount.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(820, 350, 70, 60);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("VAT                         :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(370, 360, 210, 40);

        VatNumberText.setBackground(new java.awt.Color(153, 0, 153));
        VatNumberText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VatNumberText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(VatNumberText);
        VatNumberText.setBounds(600, 420, 530, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 680);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(580, 2, 120, 0);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setAlignmentX(1.0F);
        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(5, 5, 50, 50));

        ExitMenu.setBackground(new java.awt.Color(153, 153, 153));
        ExitMenu.setBorder(null);
        ExitMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Atel Dot Net\\Desktop\\IMAGE\\icon\\bb16.png")); // NOI18N
        ExitMenu.setText(" BACK");
        ExitMenu.setDelay(100);
        ExitMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExitMenu.setMargin(new java.awt.Insets(0, 0, 0, 50));
        ExitMenu.setPreferredSize(new java.awt.Dimension(105, 19));
        ExitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMenuMouseClicked(evt);
            }
        });
        ExitMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ExitMenuKeyPressed(evt);
            }
        });
        jMenuBar1.add(ExitMenu);

        AddProductMenu.setBackground(new java.awt.Color(153, 153, 153));
        AddProductMenu.setBorder(null);
        AddProductMenu.setText("     ADD PRODUCT");
        AddProductMenu.setDelay(100);
        AddProductMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddProductMenu.setMargin(new java.awt.Insets(0, 0, 0, 50));
        AddProductMenu.setPreferredSize(new java.awt.Dimension(150, 20));
        AddProductMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProductMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(AddProductMenu);

        SellProductMenu.setBackground(new java.awt.Color(153, 153, 153));
        SellProductMenu.setBorder(null);
        SellProductMenu.setText("      SELL PRODUCT");
        SellProductMenu.setDelay(100);
        SellProductMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SellProductMenu.setMargin(new java.awt.Insets(0, 0, 0, 50));
        SellProductMenu.setPreferredSize(new java.awt.Dimension(150, 20));
        SellProductMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellProductMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(SellProductMenu);

        StockMenu.setBackground(new java.awt.Color(153, 153, 153));
        StockMenu.setBorder(null);
        StockMenu.setText("            STOCK");
        StockMenu.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        StockMenu.setDelay(100);
        StockMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StockMenu.setMargin(new java.awt.Insets(0, 0, 0, 50));
        StockMenu.setPreferredSize(new java.awt.Dimension(150, 20));
        StockMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(StockMenu);

        jMenu6.setBackground(new java.awt.Color(153, 153, 153));
        jMenu6.setBorder(null);
        jMenu6.setText("          ACCOUNT");
        jMenu6.setDelay(100);
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(0, 0, 0, 50));
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 20));

        MemberInfoItem.setText(" MEMBER INFO");
        MemberInfoItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MemberInfoItem.setMargin(new java.awt.Insets(0, 0, 0, 50));
        MemberInfoItem.setPreferredSize(new java.awt.Dimension(150, 26));
        MemberInfoItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MemberInfoItemMouseClicked(evt);
            }
        });
        MemberInfoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberInfoItemActionPerformed(evt);
            }
        });
        jMenu6.add(MemberInfoItem);

        DueBillItem.setText(" DUE BILL");
        DueBillItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DueBillItem.setMargin(new java.awt.Insets(0, 0, 0, 50));
        DueBillItem.setPreferredSize(new java.awt.Dimension(127, 26));
        DueBillItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DueBillItemMouseClicked(evt);
            }
        });
        DueBillItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DueBillItemActionPerformed(evt);
            }
        });
        jMenu6.add(DueBillItem);

        jMenuItem1.setText(" UPDATE STOCK");
        jMenuItem1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem2.setText("ALL IMPORTED ITEMS");
        jMenuItem2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuBar1.add(jMenu6);

        jMenu1.setBackground(new java.awt.Color(153, 153, 153));
        jMenu1.setText("        REFRESH");
        jMenu1.setActionCommand("    REFRESH");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1380, 744));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            
        
          Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ShopManagement;user=sa;password=123456";
            Connection con1 = DriverManager.getConnection(url);
         
            String sql1="UPDATE SHOPINFO SET ShopName=?, Address=?, Phone=?, Email=?, VAT=?, SecurityCode=?, VatNumber=?";
            
          
            PreparedStatement pst = con1.prepareStatement(sql1);
         //   pst4.setString(1, phoneNumber.getText().toString());
            
            pst.setString(1, ShopNameText.getText().toString());
           
         //   pst.setString(2, buyerName.getText().toString());
            pst.setString(2, AddressText.getText().toString());
          //  qnt = Integer.parseInt(ProductQuantity.getText().toString());
            pst.setString(3, PhoneText.getText().toString());
            pst.setString(4, EmailText.getText().toString());
           // float productPrice=Float.parseFloat(Price.getText().toString());
           String vat_st=VatText.getText().toString();
           
           float VAT=Float.parseFloat(vat_st);
            pst.setFloat(5, VAT);
            
            pst.setString(6, SecurityText.getText().toString());
            pst.setString(7, VatNumberText.getText());
          
          
            pst.executeUpdate();
           
            JOptionPane.showMessageDialog(null, "SUCCESSFULLY UPDATED");
           con1.close();
           
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMenuMouseClicked
        // TODO add your handling code here:
        UpdateStock obj=new UpdateStock();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitMenuMouseClicked

    private void ExitMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ExitMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitMenuKeyPressed

    private void AddProductMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductMenuMouseClicked
        // TODO add your handling code here:
        AddProduct obj=new AddProduct();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddProductMenuMouseClicked

    private void SellProductMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellProductMenuMouseClicked
        // TODO add your handling code here:
        SellProduct obj=new SellProduct();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellProductMenuMouseClicked

    private void StockMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMenuMouseClicked
        // TODO add your handling code here:
        StockInfo obj=new StockInfo();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StockMenuMouseClicked

    private void MemberInfoItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberInfoItemMouseClicked
        // TODO add your handling code here:
        MemberAccount obj=new MemberAccount();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MemberInfoItemMouseClicked

    private void MemberInfoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberInfoItemActionPerformed
        // TODO add your handling code here:
        MemberAccount obj=new MemberAccount();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MemberInfoItemActionPerformed

    private void DueBillItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DueBillItemMouseClicked
        // TODO add your handling code here:
        //  DueBill obj=new DueBill();
        // obj.setVisible(true);
    }//GEN-LAST:event_DueBillItemMouseClicked

    private void DueBillItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DueBillItemActionPerformed
        // TODO add your handling code here:
        DueBill obj=new DueBill();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DueBillItemActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        UpdateStock obj=new UpdateStock();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        UpdateStock obj=new UpdateStock();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        UpdateAllProducts obj=new UpdateAllProducts();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        ShopInfo obj=new ShopInfo();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    public void FetchData()
    {
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            
           Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ShopManagement;selectMethod=cursor", "sa", "123456");


            Statement statement = connection.createStatement();
            ResultSet resultSet = statement
                    .executeQuery("SELECT * FROM SHOPINFO");
            
            String Name="", Address="", Phone="", Email="", Security="", VatNum="";
            float Vat=0;
            
            while (resultSet.next()) {
                
                Name=resultSet.getString("ShopName");
                Address=resultSet.getString("Address");
                Phone=resultSet.getString("Phone");
                Email=resultSet.getString("Email");
                Vat=resultSet.getFloat("VAT");
                Security=resultSet.getString("SecurityCode");
                VatNum=resultSet.getString("VatNumber");
            }
            
           ShopNameText.setText(Name);
           AddressText.setText(Address);
           PhoneText.setText(Phone);
           EmailText.setText(Email);
           VatText.setText(""+Vat);
           SecurityText.setText(Security);
           VatNumberText.setText(VatNum);
           
           connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AddProductMenu;
    private javax.swing.JTextField AddressText;
    private javax.swing.JMenuItem DueBillItem;
    private javax.swing.JTextField EmailText;
    private javax.swing.JMenu ExitMenu;
    private javax.swing.JMenuItem MemberInfoItem;
    private javax.swing.JTextField PhoneText;
    private javax.swing.JTextField SecurityText;
    private javax.swing.JMenu SellProductMenu;
    private javax.swing.JTextField ShopNameText;
    private javax.swing.JMenu StockMenu;
    private javax.swing.JTextField VatNumberText;
    private javax.swing.JTextField VatText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
